apiVersion: v1
kind: Service
metadata:
  name: { { include "mysql-quizdb.fullname" . } }
  namespace: { { .Values.namespace } }
spec:
  clusterIP: None
  selector: { { - include "mysql-quizdb.labels" . | nindent 4 } }
  ports:
    - port: 3306
