name: Build User Microservice Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'code/user_service/**'

env:
  IMAGE_NAME: user-service
  DOCKER_USERNAME: manoharshetty507
  VIRTUAL_ENV: .venv

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: code/user_service

    steps:
    - uses: actions/checkout@v4

    - name: Install python3-venv
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-venv \
          python3-dev \
          pkg-config \
          default-libmysqlclient-dev \
          build-essential

    - name: Set Up Virtual Environment
      run: |
        python3 -m venv $VIRTUAL_ENV
        $VIRTUAL_ENV/bin/pip install --upgrade pip

    - name: Install Dependencies
      run: |
        $VIRTUAL_ENV/bin/pip install -r requirements.txt
        $VIRTUAL_ENV/bin/pip install pytest

    - name: Run Unit Tests
      run: |
        $VIRTUAL_ENV/bin/pytest -v -m "not integration"

    - name: Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build
      run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest .

    - name: Push
      run: docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
