# .github/workflows/music_service.yaml
name: Build Music Service

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'code/music_service/**'

env:
  IMAGE_NAME: music-service
  DOCKER_USERNAME: manoharshetty507

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: code/music_service
    steps:
      - uses: actions/checkout@v4
      - run: pip install pytest flask
      - run: pytest || echo "No tests found"
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKER_USERNAME --password-stdin
      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest .
      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
