apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
      - name: metrics
        image: manoharshetty507/metrics-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5012

---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: metrics
  ports:
  - port: 5012
    targetPort: 5012
