apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-cutter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-cutter
  template:
    metadata:
      labels:
        app: audio-cutter
    spec:
      containers:
      - name: audio-cutter
        image: manoharshetty507/audio-cutter-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50010
---
apiVersion: v1
kind: Service
metadata:
  name: audio-cutter-service
spec:
  selector:
    app: audio-cutter
  ports:
    - protocol: TCP
      port: 50010
      targetPort: 50010
  type: ClusterIP
